package:
  name: pypardiso
  version: "0.2.1"

source:
  git_rev: origin/master
  git_url: https://github.com/haasad/PyPardisoProject.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - mkl
    - numpy
    - scipy
    - mkl-service

about:
  home: https://github.com/haasad/PyPardisoProject
  license: BSD
  license_file: LICENSE.txt
  summary: Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations