name: conda-release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Set up miniconda with python 3.9
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        activate-environment: build
        auto-update-conda: true
    - name: Install build tools
      run: |
        conda install -c conda-forge --solver libmamba conda-build anaconda-client conda-verify grayskull
    - name: Generate conda recipe
      run: |
        grayskull pypi https://github.com/haasad/PyPardiso --sections {package,source,build,requirements,about} --strict-conda-forge
    - name: Build conda package
      run: |
        conda build PyPardiso
    - name: Upload to haasad conda channel
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "skipped release"
        #        anaconda -t ${{ secrets.CONDA_TOKEN }} upload /usr/share/miniconda/envs/test/conda-bld/noarch/*.tar.bz2
